src/AppBundle/Entity/Review.php
<?php

namespace AppBundle\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity
 * @ORM\Table(name="`review`")
 */
class Review
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue(strategy="AUTO")
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\User")
     * @ORM\JoinColumn(name="user_id", referencedColumnName="id")
     */
    private $user_id;

    /**
     * @ORM\ManyToOne(targetEntity="AppBundle\Entity\Book")
     * @ORM\JoinColumn(name="book_id", referencedColumnName="id")
     */
    private $book_id;

    /**
     * @ORM\Column(type="float")
     */
    public $rating;

    /**
     * @ORM\Column(type="string")
     */
    private $review;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date;

    /**
     * @return mixed
     */
    public function getId()
    {
        return $this->id;
    }

    /**
     * @param mixed $id
     */
    public function setId($id)
    {
        $this->id = $id;
    }

    /**
     * @return mixed
     */
    public function getUserId()
    {
        return $this->user_id;
    }

    /**
     * @param mixed $user_id
     */
    public function setUserId($user_id)
    {
        $this->user_id = $user_id;
    }

    /**
     * @return mixed
     */
    public function getRating()
    {
        return $this->rating;
    }

    /**
     * @param mixed $rating
     */
    public function setRating($rating)
    {
        $this->rating = $rating;
    }

    /**
     * @return mixed
     */
    public function getReview()
    {
        return $this->review;
    }

    /**
     * @param mixed $review
     */
    public function setReview($review)
    {
        $this->review = $review;
    }

    /**
     * @return mixed
     */
    public function getDate()
    {
        return $this->date;
    }

    /**
     * @param mixed $date
     */
    public function setDate($date)
    {
        $this->date = $date;
    }

    /**
     * @return mixed
     */
    public function getBookId()
    {
        return $this->book_id;
    }

    /**
     * @param mixed $book_id
     */
    public function setBookId($book_id)
    {
        $this->book_id = $book_id;
    }

}

src/AppBundle/Controller/DefaultController.php
<?php

namespace AppBundle\Controller;

use AppBundle\Entity\Book;
use AppBundle\Entity\Review;
use AppBundle\Form\BookType;
use DateTime;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\HttpFoundation\Request;

class DefaultController extends Controller
{
    public function indexAction()
    {
        $bookManager = $this->container->get('book_manager');

        $top5 = $bookManager->getTopFiveBooks();
        $highReview = $bookManager->getTopReviewBooks();

        return $this->render('AppBundle:Default:index.html.twig',['topFive' => $top5,'topReview'=>$highReview]);
    }

    public function googleApiSearchAction(Request $request)
    {
        $form = $this->createFormBuilder(null)
            ->add('search', TextType::class)
            ->add('submit', SubmitType::class)
            ->getForm();

        return $this->render(
            'AppBundle:GoogleApi:search.html.twig', [
            'form' => $form->createView()
        ]);
    }

    public function googleApiResultsAction(Request $request)
    {
        $form = $request->request->get('form');
        $search = $form['search'];

        $googleApiManager = $this->container->get('google_api');

        $books = $googleApiManager->getBooksFromGoogleApi($search);

        return $this->render('AppBundle:GoogleApi:results.html.twig', [
            'books' => $books
        ]);
    }

    public function googleApiViewAction(Request $request)
    {
        $isbn = $request->query->get('isbn');

        $googleApiManager = $this->container->get('google_api');

        $bookInfo = $googleApiManager->getBookInfoFromISBN($isbn);

        return $this->render('AppBundle:GoogleApi:view.html.twig', [
            'bookInfo' => $bookInfo
        ]);
    }

    public function viewAction($id)
    {
        $bookManager = $this->getBookManagerContainer();

        $genre = $bookManager->getGenreFromId($id);

        $genreList = $bookManager->getAllBookGenresWithId();

        $books = $bookManager->getBooksFromGenre($genre);

        return $this->render('AppBundle:Default:view.html.twig',
            [
                'id' => $id,
                'books' => $books,
                'genres' =>$genreList
            ]
        );
    }

    public function createAction(Request $request)
    {
        $entityManger = $this->getDoctrine()->getManager();
        $bookManager = $this->container->get('book_manager');
        $bookEntry = new Book();

        $form = $this->createForm(BookType::class, $bookEntry,
            ['action' => $request->getUri(), 'book_manager' => $bookManager]);

        $form->handleRequest($request);

        $returnView = $this->render('AppBundle:Default:create.html.twig',
            ['form' => $form->createView()]);

        if($form->isValid()) {
            $bookEntry->setTitle($bookEntry->getTitle());
            $bookEntry->setAuthor($bookEntry->getAuthor());
            $bookEntry->setSynopsis($bookEntry->getSynopsis());
            $bookEntry->setViews();
            $bookEntry->setVisible(false);
            $bookEntry->setIsbn($bookEntry->getIsbn());
            $bookEntry->setGenre($bookManager->getGenreFromId($bookEntry->getGenre()));

            /** @var UploadedFile $image */
            $image = $bookEntry->getImage();

            $filename = md5(uniqid()).'.'.$image->guessExtension();

            $image->move(
                $this->getParameter('book_cover_directory'),
                $filename
            );

            $bookEntry->setImage($filename);

            $entityManger->persist($bookEntry);
            $entityManger->flush();
            $returnView = $this->redirectToRoute("search");

        }

        return $returnView;
    }

    public function aboutAction()
    {
        return $this->render('AppBundle:Default:about.html.twig');
    }


    public function reviewAction($id, $bookId)
    {
        $bookManager = $this->getBookManagerContainer();
        $googleAPIManager = $this->container->get('google_api');

        $bookInfo = $bookManager->getBookFromId($bookId);

        $bookReviews = $bookManager->getBooksReviews($bookId, 10, 0);
        $count = count($bookReviews);
        $totalStars = 0;
        if($count>0)
        {
            $totalStars = $bookManager->getSumBook($bookId)[0][1]/$count;
        }

        $googleRating = $googleAPIManager->getBookRating($bookInfo->getTitle());

        $bookManager->updateHit($bookId);
        return $this->render('AppBundle:Default:review.html.twig',
            [
                'id' => $id,
                'bookInfo' => $bookInfo,
                'bookId' => $bookId,
                'reviews' => $bookReviews,
                'total' => $totalStars,
                'googleRating' => $googleRating
            ]
        );
    }

    public function usereviewAction($id, $bookId, Request $request)
    {
        $reviewEntry = new Review();
        $form = $this->createForm(ReviewType::class, $reviewEntry,
            [
                'action' => $request->getUri()
            ]
        );

        $form->handleRequest($request);
        $returnView = $this->render('AppBundle:Default:usereview.html.twig',['form' => $form->createView()]);

        if($form->isValid()) {
            $em = $this->getEntityManager();

            $book = $this->getBookManagerContainer()->getBookFromId($bookId);

            $reviewEntry->setUserId($this->getUser());
            $reviewEntry->setDate(new DateTime('now'));
            $reviewEntry->setRating($reviewEntry->getRating());
            $reviewEntry->setReview($reviewEntry->getReview());
            $reviewEntry->setBookId($book);

            $em->persist($reviewEntry);
            $em->flush($reviewEntry);
            $returnView = $this->redirectToRoute("book_review",array('bookId'=>$bookId,'id'=>$id));
        }
        return $returnView;
    }

    /**
     * @return BookManager|object
     */
    private function getBookManagerContainer()
    {
        return $this->container->get('book_manager');
    }

    /**
     * @return EntityManager
     */
    private function getEntityManager()
    {
        return $this->container->get('doctrine.orm.default_entity_manager');
    }
}

src/AppBundle/Resources/views/Default/about.html.twig
{% extends 'base.html.twig' %}

{% block title %}About Us{% endblock %}

{% block body %}
<div class="col-sm-6 col-xs-12 center-block panel panle-default" style="float: none;">
    <div class="panel-body">
        <h2>Click Books, the book review site</h2>
        <h3>Reviews by the readers, for the readers.</h3>
        <p>Click Book is a site designed for people who enjoy reading all types of books. We have an extensive range of literature for all types of genres.</p>
        <p>Take a look at some of the reviews posted by other readers to get an insight into the much loved books.</p>
        <p>You must be a Click Books member to write your own reviews, registration could not be easier!</p>
    </div>
</div>
{% endblock %}

src/AppBundle/Resources/views/Default/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Add New Book{% endblock %}

{% block body %}
    <h1>Add a New Book</h1>
    <div class="col-md-4 col-sm-6 col-xs-12 center-block" style="float:none;border: solid 2px #b5bbc8;padding: 20px;">
        {{ form_start(form) }}
        <div class="form-group">
            {{ form_label(form.title) }}
            {{ form_widget(form.title, {'attr': {'class':'form-control'}})}}
        </div>
        <div class="form-group">
            {{ form_label(form.author) }}
            {{ form_widget(form.author,{'attr': {'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.synopsis) }}
            {{ form_widget(form.synopsis, {'attr': {'class':'form-control' }}) }}
        </div>
        <div class="form-group" style="border: solid 2px grey; padding:10px;margin:10px;">
            {{ form_row(form.image) }}
        </div>
        <div class="form-group">
            {{ form_label(form.genre) }}
            {{ form_widget(form.genre,{'attr':{'class':'form-control'}}) }}
        </div>
        <div class="form-group">
            {{ form_label(form.isbn) }}
            {{ form_widget(form.isbn,{'attr':{'class':'form-control'}}) }}
        </div>
        {{ form_row(form.submit, { 'label': 'Request Book' },{'attr':{'class':'btn btn-block btn-primary'}}) }}
        {{ form_end(form) }}
    </div>

{% endblock %}

src/AppBundle/Resources/views/Default/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Index{% endblock %}

{% block body %}
    <div style="margin-top: 20px;" class="row">
        <div class="col-sm-3" style="margin-top: 20px;">
            <div class="panel panel-default">
                <div class="panel-heading"><h3>Quick Links</h3></div>
                <div class="panel-body">
                    <h4><a href="{{ path('search') }}">Find Books</a></h4>
                    <h4><a href="{{ path('book_review_about') }}">Who are Click Books?</a></h4>
                    <h4><a href="{{ path('fos_user_security_login') }}">Login</a></h4>
                </div>
            </div>

        </div>
        <div class="col-sm-9">
            <div class="row">
                <h2>Top 5 Books</h2>
                <hr>
                <hr>
                {% for book in topFive %}
                    <div class="col-sm-2">
                        <figure>
                            <img class="img-responsive" style="height:200px " src="{{ asset('uploads/book_covers/' ~ book.image) }}" alt="{{ book.title }} book cover"/>
                        </figure>
                        <figcaption>
                            <p>{{ book.title }}</p>
                        </figcaption>
                        </a>
                    </div>
                {% endfor %}
            </div>

            <div class="row" style="margin-top: 30px">
                <h2>Highest Votes</h2>
                <hr>
                <hr>
                {% for reviews in topReview %}
                    <div class="col-sm-2">
                        <figure>
                            <img class="img-responsive" style="height:200px " src="{{ asset('uploads/book_covers/' ~ reviews.image) }}" alt="{{ reviews.title }} book cover"/>
                        </figure>
                        <figcaption>
                            <p>{{ reviews.title|length > 20 ? reviews.title|slice(0,20) ~ '...' : reviews.title}}</p>
                            {{ reviews.sumRating|rating(5,"fa-norm") }}
                        </figcaption>
                        </a>
                    </div>
                {% endfor %}
            </div>

        </div>
    </div>

{% endblock %}

src/AppBundle/Resources/views/Default/review.html.twig
{% extends 'base.html.twig' %}

{% block title %}About the Book{% endblock %}


{% block body %}
    <h1>About the Book</h1>
    <hr>
    <hr>
    <div class="row" style="margin-top: 20px;">
        <div class="col-sm-4">
            <figure>
                <img src="{{ asset('uploads/book_covers/' ~ bookInfo.image) }}" alt="{{ bookInfo.title }} book cover">
            </figure>
        </div>
        <div class="col-sm-4">
            <div class="row">
                <h3><strong>Title</strong></h3>
                <p>{{ bookInfo.title }}</p>
            </div>
            <div class="row">
                <h3><strong>Author</strong></h3>
                <p>{{ bookInfo.author }}</p>
            </div>
            <div class="row">
                <h3><strong>Genre</strong></h3>
                <p>{{ bookInfo.genre }}</p>
            </div>
            <div class="row">
                <h3><strong>Google Rating</strong></h3>
                <p>{{ googleRating }} / 5</p>
            </div>
        </div>
        <div class="col-sm-4">
            <div class="panel panel-default">
                <div class="panel-heading">Average Review</div>
                <div class="panel-body">
                    {{ total|rating }}
                    {% if is_granted('ROLE_USER') or is_granted('ROLE_ADMIN') or is_granted('ROLE_MODERATOR') %}

                        <a class="btn-default btn btn-block" href="{{ path('book_user_review', {'id': id, 'bookId': bookInfo.id}) }}">Leave A Review</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>

    <div class="row col-sm-12" style="margin-top: 20px;">
        <h2><strong>Synopsis</strong></h2>
        <p>{{ bookInfo.synopsis}}</p>
    </div>


    <div class="row" style="margin-top: 50px;">
        <h3>Reviews</h3>
        {% for review in reviews %}
            <div style="margin-top:20px;background-color: #D3D3D3;border: solid black 5px;box-shadow: 10px 10px 5px grey;" class="col-sm-6 col-xs-12">
                <p>{{ review.userId.firstname }}</p>
                <p>{{ review.date|date("m/d/Y") }}</p>
                {{ review.rating|rating }}
                <p>{{ review.review }}</p>
                {% if is_granted('ROLE_MODERATOR') %}
                    <form method="post" action="{{ path('delete_review') }}">
                        <input type="hidden" name="id" value="{{ review.id }}">
                        <input type="submit" value="Delete">
                    </form>
                {% endif %}
            </div>
        {% endfor %}
    </div>
{% endblock %}

src/AppBundle/Resources/views/Default/usereview.html.twig
{% extends 'base.html.twig' %}

{% block title %}REVIEW{% endblock %}

{% block body %}

    <h1>Review</h1>

    {{ form(form) }}

{% endblock %}

src/AppBundle/Resources/views/Default/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Books View{% endblock %}

{% block body %}
    <div class="row" style="margin-top: 20px">
        <div class="col-sm-3">
            {#group sections#}
            <div class="panel-group">
                <div class="panel panel-primary">
                    <div class="panel-heading">Search</div>
                    <div class="panel-body">{{ render(controller('AppBundle:Post:search')) }}</div>
                </div>
                <div class="panel panel-primary">
                    <div class="panel-heading">Find by Genre</div>
                    <div class="panel-body">
                        <ul style="list-style: none;">
                            {% for genreItems in genres %}
                                <li style="margin-top: 10px;"><a href="{{ path('book_review_book_view', {'id':genreItems.id}) }}">{{ genreItems.genre }}</a></li>
                            {% endfor %}
                        </ul>

                    </div>
                </div>
            </div>

        </div>
        <div class="col-sm-9">
            {% for book in books %}
                <div class="col-sm-3" style="margin-top: 40px; ">
                    <img class="img-responsive" style="height:200px " src="{{ asset('uploads/book_covers/' ~ book.image) }}" alt="{{ book.title }} book cover"/>
                    <a href="{{ path('book_review', {'id': id, 'bookId': book.id}) }}">
                        {{ book.title|length > 20 ? book.title|slice(0,20) ~ '...' : book.title}}
                    </a>
                </div>
            {% endfor %}
        </div>
    </div>

{% endblock %}